### ISSUE TITLE
Getting error installing pakage

### ISSUE THREAD

**Issue by apu248** [msach22/opentok-ionic-samples#2]
ionic cordova plugin add https://github.com/msach22/cordova-plugin-opentok/
> cordova plugin add https://github.com/msach22/cordova-plugin-opentok/ --save
Error: Failed to fetch plugin https://github.com/msach22/cordova-plugin-opentok/ via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm ERR! code ENOGIT
npm ERR! No git binary found in $PATH
npm ERR!
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Vaibhav\AppData\Roaming\npm-cache\_logs\2017-11-30T11_01_45_338Z-debug.log

[ERROR] An error occurred while running cordova plugin add
        https://github.com/msach22/cordova-plugin-opentok/ --save (exit code 1).

**Comment by msach22** [comment]
Hi @apu248 I just tested installing the plugin and I'm able to do so. Did you create an Ionic project using `ionic start {appName}`?  Could you try creating a fresh Ionic project and try installing the plugin?

**Comment by apu248** [comment]
Not able to install it again. created blank ionic proj

here is the stack trace

Your environment has been set up for using Node.js 8.9.1 (x64) and npm.

C:\Users\Vaibhav>ionic start abc

? What starter would you like to use: blank
√ Creating directory .\abc - done!
√ Downloading and extracting blank starter - done!

? Would you like to integrate your new app with Cordova to target native iOS an
d Android? Yes
√ Personalizing ionic.config.json and package.json - done!
> ionic integrations enable cordova --quiet
[ERROR] Error with .\abc\node_modules\ionic-angular\package.json file:
        FILE_NOT_FOUND
[ERROR] Error with .\abc\node_modules\@ionic\app-scripts\package.json file:
        FILE_NOT_FOUND
√ Downloading integration cordova - done!
√ Copying integrations files to project - done!
[OK] Added cordova integration!

Installing dependencies may take several minutes.

  *   IONIC  DEVAPP  *

 Speed up development with the Ionic DevApp, our fast, on-device testing mobile app

  -     Test on iOS and Android without Native SDKs
  -     LiveReload for instant style and JS updates

 ️-->    Install DevApp: https://bit.ly/ionic-dev-app    <--

> npm i
√ Running command - done!
> git init

  *   IONIC  PRO  *

 Supercharge your Ionic development with the Ionic Pro SDK

  -     Track runtime errors in real-time, back to your original TypeScript
  -     Push remote updates and skip the app store queue

Learn more about Ionic Pro: https://ionicframework.com/products

? Install the free Ionic Pro SDK and connect your app? No

-----------------------------------

> git add -A
> git commit -m "Initial commit" --no-gpg-sign
[ERROR] An error occurred while running git commit -m "Initial commit"

        --no-gpg-sign (exit code 128):


        *** Please tell me who you are.

        Run

           git config --global user.email "you@example.com"
           git config --global user.name "Your Name"

        to set your account's default identity.
        Omit --global to set the identity only in this repository.

        fatal: unable to auto-detect email address (got
        'Vaibhav@Kulkarni.(none)')



C:\Users\Vaibhav>git config --global user.email 'apurva.wable@gmail.com'

C:\Users\Vaibhav>git config --gloabl user.name 'apurva'
error: unknown option `gloabl'
usage: git config [<options>]

Config file location
    --global              use global config file
    --system              use system config file
    --local               use repository config file
    -f, --file <file>     use given config file
    --blob <blob-id>      read config from given blob object

Action
    --get                 get value: name [value-regex]
    --get-all             get all values: key [value-regex]
    --get-regexp          get values for regexp: name-regex [value-regex]
    --get-urlmatch        get value specific for the URL: section[.var] URL
    --replace-all         replace all matching variables: name value [value_regex]
    --add                 add a new variable: name value
    --unset               remove a variable: name [value-regex]
    --unset-all           remove all matches: name [value-regex]
    --rename-section      rename section: old-name new-name
    --remove-section      remove a section: name
    -l, --list            list all
    -e, --edit            open an editor
    --get-color           find the color configured: slot [default]
    --get-colorbool       find the color setting: slot [stdout-is-tty]

Type
    --bool                value is "true" or "false"
    --int                 value is decimal number
    --bool-or-int         value is --bool or --int
    --path                value is a path (file or directory name)

Other
    -z, --null            terminate values with NUL byte
    --name-only           show variable names only
    --includes            respect include directives on lookup
    --show-origin         show origin of config (file, standard input, blob, command line)


C:\Users\Vaibhav>git config --global user.name 'apurva'

C:\Users\Vaibhav>cd abc

C:\Users\Vaibhav\abc>npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 115 packages in 24.805s

C:\Users\Vaibhav\abc>ionic cordova plugin add https://github.com/msach22/cordova-plugin-opentok/
√ Creating .\www directory for you - done!
> cordova plugin add https://github.com/msach22/cordova-plugin-opentok/ --save
Error: Failed to fetch plugin https://github.com/msach22/cordova-plugin-opentok/ via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm ERR! code 1
npm ERR! Command failed: C:\Program Files\Git\cmd\git.EXE submodule update -q --init --recursive
npm ERR! C:\Program Files\Git\mingw64/libexec/git-core\git-submodule: line 7: basename: command not found
npm ERR! C:\Program Files\Git\mingw64/libexec/git-core\git-submodule: line 7: sed: command not found
npm ERR! C:\Program Files\Git\mingw64/libexec/git-core\git-submodule: line 19: .: git-sh-setup: file not found
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Vaibhav\AppData\Roaming\npm-cache\_logs\2017-11-30T16_44_34_917Z-debug.log

[ERROR] An error occurred while running cordova plugin add
        https://github.com/msach22/cordova-plugin-opentok/ --save (exit code 1).

C:\Users\Vaibhav\abc>

**Comment by apu248** [comment]
ionic start abc

? What starter would you like to use: blank
√ Creating directory .\abc - done!
√ Downloading and extracting blank starter - done!

? Would you like to integrate your new app with Cordova to target native iOS an
d Android? Yes
√ Personalizing ionic.config.json and package.json - done!
> ionic integrations enable cordova --quiet
[ERROR] Error with .\abc\node_modules\ionic-angular\package.json file:
        FILE_NOT_FOUND
[ERROR] Error with .\abc\node_modules\@ionic\app-scripts\package.json file:
        FILE_NOT_FOUND
√ Downloading integration cordova - done!
√ Copying integrations files to project - done!
[OK] Added cordova integration!

Installing dependencies may take several minutes.

  *   IONIC  DEVAPP  *

 Speed up development with the Ionic DevApp, our fast, on-device testing mobile app

  -     Test on iOS and Android without Native SDKs
  -     LiveReload for instant style and JS updates

 ️-->    Install DevApp: https://bit.ly/ionic-dev-app    <--

> npm i
√ Running command - done!
> git init

  *   IONIC  PRO  *

 Supercharge your Ionic development with the Ionic Pro SDK

  -     Track runtime errors in real-time, back to your original TypeScript
  -     Push remote updates and skip the app store queue

Learn more about Ionic Pro: https://ionicframework.com/products

**Comment by yelji** [comment]
Failed to install 'com.tokbox.cordova.opentok': CordovaError: Using "requireCordovaModule" to load non-cordova module "q" is not supported. Instead, add this module to your dependencies and use regular "require" to load it.
    at Context.requireCordovaModule (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/Context.js:57:15)
    at module.exports (/Users/lavangiri/Downloads/for ios/plugins/com.tokbox.cordova.opentok/scripts/downloadiOSSDK.js:7:21)
    at runScriptViaModuleLoader (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:157:32)
    at runScript (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:136:12)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:108:40

I got this error
